/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrms.GUI;

import hrms.MysqlConnect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Islam
 */
public class Incentives extends javax.swing.JFrame {

      String date,precentage,HealthInsurance=".1",taxs=".03";
 Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    
    /**
     * Creates new form Incentives
     */
    public Incentives() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtprece = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtXDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Incentive :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 11, 83, 21);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrms/GUI/pics/FRaij7m.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(4, 0, 390, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 390, 50));

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Percentage : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 12, 96, 30);

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adoption date :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 60, 96, 30);

        txtprece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreceActionPerformed(evt);
            }
        });
        jPanel2.add(txtprece);
        txtprece.setBounds(110, 8, 51, 30);

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("%");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(165, 11, 32, 32);
        jPanel2.add(txtXDate);
        txtXDate.setBounds(110, 61, 137, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrms/GUI/pics/FRaij7m.jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(4, 0, 390, 140);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 390, 140));

        jPanel3.setLayout(null);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(296, 11, 84, 32);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrms/GUI/pics/FRaij7m.jpg"))); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(-6, 4, 400, 60);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 390, 70));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreceActionPerformed

private void get()
{

         precentage=txtprece.getText();
         date=txtXDate.getDate().toString();         
}

/*private boolean check(){
        boolean f=true;
          if("".equalsIgnoreCase(txtprece.getText()))
        //{Lperce.setText("unvalid precentage");     f=false;}else{Lperce.setText("");  }
       //try{ if("".equalsIgnoreCase(txtXDate.getDate().toString())){
          //  ldate.setText("unvalid Date");     f=false;}else{ldate.setText("");  }}
         //  catch(Exception e){
               
                          Lperce.setText("unvalid precentage");
       
           }
return f;
}*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 get(); 
        System.out.println(precentage+taxs+date+HealthInsurance);
////       Financial i =new Financial();
////    i.incentives(HealthInsurance, taxs, precentage, date);

       con=new MysqlConnect().ConnectDB();
       String ins="INSERT INTO `hrms`.`finextra` (`Taxs`, `HealthInsurance`,`Incentives`, `precntagedate`) VALUES ('"+taxs+"','"+HealthInsurance+"','"+precentage+"','"+date+"')";
        
         try {
             ps=con.prepareStatement(ins);
             ps.execute();
             JOptionPane.showMessageDialog(null,"Added Successfully");
             } catch (HeadlessException | SQLException ex) {
             JOptionPane.showMessageDialog(null, ex);
        }
                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Incentives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Incentives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Incentives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Incentives.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Incentives().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private org.jdesktop.swingx.JXDatePicker txtXDate;
    private javax.swing.JTextField txtprece;
    // End of variables declaration//GEN-END:variables
}
